name: Install Package, Lint Code & Run Tests on Mac

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  install-lint-test-on-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version:  # github.com/actions/python-versions/releases
          - 3.12
          - 3.13

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4  # github.com/actions/checkout

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5  # github.com/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: make get-poetry

      - name: Install Package & Dependencies
        run: make install

      - name: Lint Code
        run: make lint

      - name: Run Tests
        run: make test
        env:
          LEPTON_API_KEY: ${{ secrets.LEPTON_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
